export const Sector = {
  TECHNOLOGY: 'TECHNOLOGY',
  ENERGY: 'ENERGY',
  HEALTHCARE: 'HEALTHCARE',
  FINANCIALS: 'FINANCIALS',
  CONSUMER: 'CONSUMER',
  INDUSTRIALS: 'INDUSTRIALS',
  MATERIALS: 'MATERIALS',
  UTILITIES: 'UTILITIES',
  REAL_ESTATE: 'REAL_ESTATE',
  COMMUNICATION: 'COMMUNICATION',
} as const;

export type Sector = (typeof Sector)[keyof typeof Sector];
